ProjectAgileWeb7/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectAgileWeb7.Data;
using ProjectAgileWeb7.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ProjectAgileWeb7.Controllers
{
    [Authorize]
    public class FavoritesController : Controller
    {
        private readonly ApplicationDbContext _appContext;
        private readonly UserManager<ApplicationUser> _userManager;
        [BindProperty]
        public ApplicationUser CurrentUser { get; set; }
        [BindProperty]
        public Hotel SelectedHotel { get; set; }

        public FavoritesController(ApplicationDbContext appContext, UserManager<ApplicationUser> userManager)
        {
            _appContext = appContext;
            _userManager = userManager;
        }

        public async Task<IActionResult> GetHotelIdFromIndex(int id)
        {
            CurrentUser = await _userManager.GetUserAsync(User);
            string currentUserId = CurrentUser.Id;

            CheckIfHotelIsFavorite(id, currentUserId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetHotelIdFromFavorites(int id)
        {
            CurrentUser = await _userManager.GetUserAsync(User);
            string currentUserId = CurrentUser.Id;

            CheckIfHotelIsFavorite(id, currentUserId);
            return RedirectToAction("Favorites");
        }

        private void CheckIfHotelIsFavorite(int id, string currentUserId)
        {
            SelectedHotel = _appContext.Hotels.Where(h => h.HotelId == id)
                                    .Include(h => h.HotelFacilities)
                                    .ThenInclude(hf => hf.Facility)
                                    .FirstOrDefault();

            List<int> hotelIdList = GetHotelIdList(currentUserId);

            if (hotelIdList.Contains(id))
            {
                var oldHotelUser = _appContext.HotelUsers
                                   .Where(hu => hu.UserId == currentUserId)
                                   .Where(hu => hu.HotelId == id)
                                   .FirstOrDefault();
                _appContext.HotelUsers.Remove(oldHotelUser);
                _appContext.SaveChanges();
            }
            else
            {
                var newHotelUser = new HotelUser
                {
                    UserId = currentUserId,
                    ApplicationUser = CurrentUser,
                    HotelId = id,
                    Hotel = SelectedHotel
                };
                _appContext.HotelUsers.Add(newHotelUser);
                _appContext.SaveChanges();
            }
        }

        public IActionResult Favorites()
        {
            string currentUserId = GetCurrentUserId();
            var currentUser = _appContext.ApplicationUsers.Where(u => u.Id == currentUserId).FirstOrDefault();
            ViewBag.User = currentUser;
            var newHotelsList = _appContext.HotelUsers
                                    .Where(x => x.UserId == currentUserId)
                                    .Include(hu => hu.Hotel)
                                    .ThenInclude(h => h.HotelFacilities)
                                    .ThenInclude(hf => hf.Facility)
                                    .Select(x => x.Hotel)
                                    .ToList();
            List<int> hotelIdList = GetHotelIdList(currentUserId);
            var newHotelViewModel = new HotelsViewModel
            {
                Hotels = newHotelsList,
                FavoriteHotels = hotelIdList
            };

            return View(newHotelViewModel);
        }

        private List<int> GetHotelIdList(string currentUserId)
        {
            return _appContext.HotelUsers
                                       .Where(x => x.UserId == currentUserId)
                                       .Select(x => x.HotelId)
                                       .ToList();
        }

        private string GetCurrentUserId()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var identityClaimUser = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = identityClaimUser?.Value;
            return currentUserId;
        }
    }
}

ProjectAgileWeb7/Controllers/HotelDetailsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProjectAgileWeb7.Data;
using ProjectAgileWeb7.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectAgileWeb7.Controllers
{
    [Authorize]
    public class HotelDetailsController : Controller
    {
        private readonly ApplicationDbContext _appContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public HotelDetailsController(ApplicationDbContext appContext,
            UserManager<ApplicationUser> userManager)
        {
            _appContext = appContext;
            _userManager = userManager;
        }

        [BindProperty]
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [BindProperty]
        public ApplicationUser CurrentUser { get; set; }
        [BindProperty]
        public Payment Payment { get; set; }

        public async Task<IActionResult> HotelPage(int id)
        {
            var hotel = await _appContext.Hotels
                .Where(h => h.HotelId == id)
                .Include(r => r.Rooms)
                .Include(f => f.HotelFacilities)
                .ThenInclude(fa => fa.Facility)
                .ToListAsync();

            List<DateTime> daysRangeList = GetStayingDaysRangeList();
            ViewBag.DataInfo = daysRangeList;

            var unavailableRooms = _appContext.Rooms
                                    .Where(r => _appContext.BookedRooms
                                    .Any(b => b.RoomId == r.RoomId && daysRangeList.Contains(b.Date)));

            var availableRoomsToBeBooked = _appContext.Rooms.Except(unavailableRooms)
                                                .Where(r => r.HotelId == id);

            ViewBag.RoomsAvailable = availableRoomsToBeBooked.ToList();
            return View(hotel[0]);
        }

        public async Task<IActionResult> BookRoom(RoomType roomType, int id)
        {
            CurrentUser = await _userManager.GetUserAsync(User);
            if (CurrentUser != null)
                ViewBag.User = CurrentUser;

            List<DateTime> daysRangeList = GetStayingDaysRangeList();
            ViewBag.DataInfo = daysRangeList;

            var unavailableRooms = _appContext.Rooms
                .Where(r => _appContext.BookedRooms
                .Any(b => b.RoomId == r.RoomId && daysRangeList.Contains(b.Date)));

            var availableRoomToBeBooked = _appContext.Rooms
                .Except(unavailableRooms)
                .Include(h => h.Hotel)
                .Where(r => r.HotelId == id)
                .Where(r => r.RoomType == roomType)
                .FirstOrDefault();

            if (availableRoomToBeBooked != null)
            {
                HttpContext.Session.SetInt32("roomId", availableRoomToBeBooked.RoomId);
                return View(availableRoomToBeBooked);
            }
            else
            {
                return (NotFound());
            }
        }

        private List<DateTime> GetStayingDaysRangeList()
        {
            var checkInDate = Convert.ToDateTime(JsonConvert.DeserializeObject(HttpContext.Session.GetString("CheckInDate")));
            var checkOutDate = Convert.ToDateTime(JsonConvert.DeserializeObject(HttpContext.Session.GetString("CheckOutDate")));
            var daysRangeList = new List<DateTime>();

            for (DateTime date = checkInDate; date <= checkOutDate; date = date.AddDays(1))
            {
                daysRangeList.Add(date);
            }
            return daysRangeList;
        }
    }
}

ProjectAgileWeb7/Views/Favorites/Favorites.cshtml
@model ProjectAgileWeb7.Models.HotelsViewModel
@{
    ViewData["Title"] = "Favorites";
}

<div class="card border-0">
    <div class="card-body border-0 p-0">
        <a asp-area="Identity" asp-page="/Account/Manage/Index" class="btn btn-outline-primary float-right"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back to Profile</a>

    </div>
    <div class="card-header bg-white pt-0 border-0 h1">
        Favorite hotels
    </div>
    <div class="card-body bg-white pt-0 pb-0 border-0 h5">
        Dear <span>
            @if (ViewBag.User.LastName == null && ViewBag.User.FirstName == null)
            {

                @ViewBag.User.UserName
            }
            else
            {
                @Html.Raw($"{@ViewBag.User.FirstName} {@ViewBag.User.LastName}")
            },
        </span> you have
        <span>
            @if (@Model.Hotels.Count() == 0)
            {
                <span> no favorite hotels </span>
            }
            else if (@Model.Hotels.Count() == 1)
            {
                <span>1 favorite hotel </span>
            }
            else
            {
                <span> @Model.Hotels.Count() favorite hotels </span>
            }
        </span> saved on your account.
    </div>
</div>

@if (@Model.Hotels.Count() > 0)
{

    <div class="container  p-0 m-0">
        @foreach (var hotel in @Model.Hotels)
        {
            <div class="card-deck">
                <div class="card mt-4">
                    <div class="card-header m-0 pb-0 border-bottom-0 bg-white">
                        <a asp-controller="Favorites" asp-action="GetHotelIdFromFavorites" asp-route-id="@hotel.HotelId" class="btn btn-lg float-right @(Model.FavoriteHotels.Contains(@hotel.HotelId) ? "text-success" : "text-dark")" id="favorite-button"><i class="fas fa-heart"></i></a>
                    </div>
                    <div class="card-body pb-0 pt-0 d-flex">
                        <div class="text-center">
                            <img class="hotel-image" src=@Url.Content(hotel.ImageUrl) />
                        </div>
                        <div class="ml-3">
                            <div>
                                <h2 class="hotel-name">
                                    @hotel.Name
                                </h2>
                            </div>
                            <div>
                                @for (var i = 0; i < hotel.Stars; i++)
                                {
                                    <i class="fas fa-star text-warning "></i>
                                }
                            </div>
                            <div>
                                <p>
                                    @hotel.Address, @hotel.ZipCode, @hotel.City, @hotel.Country
                                </p>
                                <p>
                                    Distance from centre: @hotel.DistanceFromCenter km.
                                </p>
                            </div>
                            <div class="card-text text-justify">
                                <p>@hotel.Description</p>
                            </div>
                            <div>
                                <p>
                                    Facilities: &nbsp;
                                    @foreach (var facility in hotel.HotelFacilities)
                                    {
                                        <span class="mr-1">@facility.Facility.Name</span>
                                    }
                                </p>
                            </div>
                            <div class="card-text">
                                <p> <a href="@hotel.Website">@hotel.Website</a></p>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer pt-0 pl-0 border-top-0 bg-white">
                        <a asp-controller="HotelDetails" asp-action="HotelPage" asp-route-id="@hotel.HotelId" class="btn my-button  btn-lg btn-success float-right ">See details</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <a asp-action="Index" asp-controller="Home" class="btn btn-primary mt-2">Back to homepage</a>
}